- name: Initialize cluster
  command: galera_new_cluster

- name: Create main database
  mysql_db: name={{ main_db }} state=present

- name: Create test database
  mysql_db: name={{ test_db }} state=present

- name: Create main user
  mysql_user:
        login_user=root
        name={{ main_user_name }}
        password={{ main_user_pass }}
        priv=*.*:ALL
        host=%

- name: Create test user
  mysql_user:
        login_user=root
        name={{ test_user_name }}
        password={{ test_user_pass }}
        priv=*.*:ALL
        host=%

- name: Create test user
  mysql_user:
        login_user=root
        name=haproxy
        priv=*.*:ALL
        host=%
